export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ChatPage } from './ChatPage'
export { default as SettingsPage } from './SettingsPage'
export { default as FriendsPage } from './FriendsPage'
export { default as ProfilePage } from './ProfilePage'
export { default as NotFoundPage } from './NotFoundPage'